name: Profile Readme Development Stats

on:
  schedule:
    # Runs at 12am IST
    - cron: '12 15 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V3
